configuracion_busqueda:
  cv: 5
  n_iter: 50
  random_state: 42
  scoring: recall
mejor_puntuacion: !!python/object/apply:numpy._core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  47JioIQ36j8=
mejores_parametros:
  C: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAABAj0A=
  gamma: scale
  kernel: rbf
modelo: SVM
